# This will run unit / integration and e2e tests

name: Test

on:
  pull_request:
    types: [opened, edited, synchronize]

  workflow_dispatch:

jobs:
  # This will start unit/integration testing
  # test-unit:
  #   name: Unit
  #   strategy:
  #     matrix:
  #       version: [20, 18]
  #       platform: [ubuntu-latest]

  #   runs-on: ${{ matrix.platform }}

  #   steps:
  #     - name: Get code
  #       uses: actions/checkout@v4

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Instal SAP CDS-DK
  #       run: npm i -g @sap/cds-dk ts-node

  #     - name: Start unit / integration tests
  #       run: npm run test:unit

  # This will start the e2e tests with a live server
  test-e2e:
    name: End-to-end (e2e)
    # needs: test-unit
    strategy:
      matrix:
        version: [20, 18]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm install -g @sap/cds-dk ts-node typescript
          npm install

      - name: Start server and start e2e tests
        run: npm run test:e2e

  # This decorator is a special decorator which needs an extensive testing due to creation of:
  # - @dispatcher folder
  # - injection of @dispatcher folder inside of the package.json - imports
  # - injection of @dispatcher folder inside of the tsconfig.json - include
  # - injection of @dispatcher folder inside of the .gitignore
  test-env-decorator:
    name: Test @Env decorator
    strategy:
      matrix:
        version: [20, 18]
        platform: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm install -g @sap/cds-dk ts-node typescript
          npm install

      - name: Verify @decorator folder, index.ts file, and content
        run: ts-node ./postinstall/util/Verifier.ts
